"""Role update

Revision ID: 26fbcc1c2590
Revises: 29645ae9c309
Create Date: 2015-09-24 12:45:24.170127

"""

# revision identifiers, used by Alembic.
revision = '26fbcc1c2590'
down_revision = '29645ae9c309'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
