"""confirm

Revision ID: 3d5e64200c9
Revises: None
Create Date: 2015-09-20 15:02:50.392660

"""

# revision identifiers, used by Alembic.
revision = '3d5e64200c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
